config/routes.rb
Rails.application.routes.draw do

  resources :volunteer_resources do
    member do
      get :file
    end
  end

  get 'resources', to: 'dashboard#resources'
  resources :answers
  resources :questions

  resources :schools do
    collection do
      get 'my-school', action: :my_school
    end
  end

  resources :appointments
  get 'my-appointments', to: 'appointments#my_appointments', as: 'my_appointments'
  get 'appointment-search', to: 'appointments#search'
  get 'incomplete-appointments', to: 'appointments#incomplete'

  resources :volunteers
  resources :conversations

  scope module: 'static' do
    get :home
    get :team
    get :donate
    get :contact
  end

  post :contact, to: 'static#contact_submit'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :users do
    collection do
      get :new_volunteer
      post :create_volunteer
      get 'my-volunteers', action: :my_volunteers
      get 'pending-volunteers', action: :my_pending_volunteers
    end
  end

  resources :conversations do
    member do
      post :delete
    end
  end

  get 'dashboard', to: 'dashboard#show'
  get 'pending', to: 'dashboard#pending'
  get 'profile', to: 'dashboard#profile'
  get 'aggregate-report', to: 'dashboard#aggregate_report'
  patch 'change_password', to: 'dashboard#change_password', as: 'change_password'

  root 'static#home'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :check_admin!, only: [:aggregate_report]
  before_action :check_user!, except: :pending
  before_action :authenticate_user!

  def pending
  end

  def show
    @conversations = current_user.conversations.current
  end

  def profile
  end

  def aggregate_report
  end

  def resources
    @resources = VolunteerResource.current
  end

  def change_password
    if current_user.update_with_password(user_password_params)
      sign_in current_user, bypass: true
      redirect_to profile_path, notice: "Your password has been successfully changed."
    else
      render :profile
    end
  end

  private
  def user_password_params
    params.required(:user).permit(:password, :password_confirmation, :current_password)
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/aggregate_report.html.haml
.content-header
  .container
    %h1 Aggregate Data

.container
  .row
    .content-container
      %h3 In the last week:
      %p= pluralize User.where("last_sign_in_at > ?", Time.now.last_week).count, 'volunteer'
      %p= pluralize Appointment.where("created_at > ?", Time.now.last_week).count, 'shift'
      %p= pluralize Conversation.where("created_at > ?", Time.now.last_week).count, 'connection'

app/views/dashboard/pending.html.haml
.content-header
  .container
    %h1 Thank You!

.container
  .content-container
    %br
    %br
    %p.lead.centered
      Thank you for registering, we will notify you when you've been approved!
    %br
    %br

app/views/dashboard/profile.html.haml
.content-header
  .container
    %h1 Your Profile
    %p= link_to 'Back to Dashboard', dashboard_path

.container
  .content-container
    = form_for current_user, url: user_path(current_user), method: :patch, html: { class: 'form-horizontal' } do |f|
      - if current_user.errors.any?
        #error_explanation
          %h2
            = pluralize(current_user.errors.count, "error")
            prohibited this profile from being saved:
          %ul
            - current_user.errors.full_messages.each do |message|
              %li= message
      .form-group
        = f.label :first_name, class: 'control-label col-md-3'
        .col-md-6
          = f.text_field :first_name, class: 'form-control'
      .form-group
        = f.label :last_name, class: 'control-label col-md-3'
        .col-md-6
          = f.text_field :last_name, class: 'form-control'
      .form-group
        = f.label :email, class: 'control-label col-md-3'
        .col-md-6
          = f.text_field :email, class: 'form-control'
      .form-group
        = f.label :phone, class: 'control-label col-md-3'
        .col-md-6
          = f.text_field :phone, class: 'form-control'
      .form-group
        = f.label :race, 'Race/Ethnicity', class: 'control-label col-md-3'
        .col-md-6
          = f.select :race, [['---', nil]] + User::RACE, {}, class: 'form-control'
      .form-group
        = f.label :familiar_communities, 'Communities You Know Well', class: 'control-label col-md-3'
        .col-md-6
          = f.text_area :familiar_communities, placeholder: "List all NJ communities that you're familiar with here (e.g. your hometown, a specific faith-based community)", rows: 4, class: 'form-control'
      .form-group
        = f.label :language_one, class: 'control-label col-md-3'
        .col-md-6
          = f.text_field :language_one, class: 'form-control'
      .form-group
        = f.label :language_two, class: 'control-label col-md-3'
        .col-md-6
          = f.text_field :language_two, class: 'form-control'
      .form-group
        = f.label :language_three, class: 'control-label col-md-3'
        .col-md-6
          = f.text_field :language_three, class: 'form-control'
      - if current_user.admin?
        .form-group
          = f.label :school_id, class: 'control-label col-md-3'
          .col-md-6
            = f.select :school_id, [['---', nil]] + School.order(:name).pluck(:name, :id), {}, class: 'form-control'
      - else
        .form-group
          %label.control-label.col-md-3 School
          .col-md-6
            .form-control= current_user.school.name if current_user.school.present?
      .form-group
        .col-md-6.col-md-offset-3
          = f.submit nil, class: 'btn btn-primary'

  .content-container
    = form_for current_user, url: change_password_path, html: { class: 'form-horizontal' } do |f|
      .form-group
        = f.label :current_password, class: 'col-sm-3 control-label'
        .col-sm-6
          = f.password_field :current_password, class: 'form-control', placeholder: 'Current password'
          - if errors = current_user.errors[:current_password] and errors.present?
            .bs-callout.bs-callout-danger
              Please enter your
              %strong current
              password in order to set a new password.
      .form-group
        = f.label :password, class: 'col-sm-3 control-label'
        .col-sm-6
          = f.password_field :password, class: 'form-control', placeholder: "New password"
          - if errors = current_user.errors[:password] and errors.present?
            .bs-callout.bs-callout-danger
              Please enter a new password that is at least 8 characters long.
      .form-group
        .col-md-6.col-md-offset-3
          = f.submit 'Change Password', class: 'btn btn-primary'

app/views/dashboard/resources.html.haml
.content-header
  .container
    %h1 Resources
    %p= link_to 'Back to dashboard', dashboard_path

.container
  - @resources.each do |resource|
    = render resource
    %hr

app/views/dashboard/show.html.haml
.content-header
  .container
    %h1
      Welcome
      = succeed '!' do
        = current_user.first_name.present? ? current_user.first_name : 'to your dashboard'

- unless current_user.profile_complete?
  .dashboard-alert
    .container
      %h3
        Looks like your profile is missing information - please
        = link_to 'update your profile', profile_path
        immediately!

- if VolunteerResource.current.present?
  .dashboard-alert
    .container
      %h3
        There are new
        = link_to 'resources', resources_path
        available!

- if current_user.campus_captain? and User.where(approved: false, school_id: current_user.school_id).present?
  .dashboard-alert
    .container
      %h3
        There are new
        = link_to 'campus volunteers', pending_volunteers_users_path
        waiting for your approval!

.container
  .row
    .col-sm-3.col-xs-4
      .dashboard-icon
        = link_to new_conversation_path do
          = image_tag 'img/icons/conversations.png', class: 'img-responsive'
      %p.lead
        You've added
        = current_user.conversations.count
        connections so far
    .col-sm-3.col-xs-4
      .dashboard-icon
        = link_to new_appointment_path do
          = image_tag 'img/icons/appointment.png', class: 'img-responsive'
      %p.lead
        Your campus has
        = pluralize(Appointment.where(created_by_id: current_user.id).where("date > ?", Date.current).count, 'shift')
        coming up
    - if current_user.appointments.incomplete.present?
      .col-sm-3.col-xs-4
        .dashboard-icon
          = link_to incomplete_appointments_path do
            = image_tag 'img/icons/appointment.png', class: 'img-responsive'
        %p.lead
          You have incomplete shifts!
    .col-sm-3.col-xs-4
      .dashboard-icon
        - send_to = User.where(school: current_user.school, campus_captain: !current_user.campus_captain?).pluck(:email).join(',')
        = link_to "mailto:#{send_to}" do
          = image_tag 'img/icons/email.png', class: 'img-responsive'
      %p.lead
        Connect with your
        = current_user.campus_captain? ? 'volunteers' : 'campus captain'
    .col-sm-3.col-xs-4
      .dashboard-icon
        = link_to profile_path do
          = image_tag 'img/icons/settings.png', class: 'img-responsive'
      %p.lead
        Profile
  .row
    - if current_user.campus_captain?
      .col-sm-3
        .dashboard-icon
          = link_to new_volunteer_users_path do
            = image_tag 'img/icons/volunteer.png', class: 'img-responsive'
        %p.lead
          Your campus has registered
          = pluralize(User.where(school: current_user.school).count, 'volunteer')
    - if current_user.admin?
      .col-sm-3
        .dashboard-icon
          = link_to schools_path do
            = image_tag 'img/icons/volunteer.png', class: 'img-responsive'
        %p.lead
          Admin overview of all schools
      .col-sm-3
        .dashboard-icon
          = link_to aggregate_report_path do
            = image_tag 'img/icons/volunteer.png', class: 'img-responsive'
        %p.lead
          Admin overview of recent activity