config/routes.rb
Rails.application.routes.draw do

  resources :volunteer_resources do
    member do
      get :file
    end
  end

  get 'resources', to: 'dashboard#resources'
  resources :answers
  resources :questions

  resources :schools do
    collection do
      get 'my-school', action: :my_school
    end
  end

  resources :appointments
  get 'my-appointments', to: 'appointments#my_appointments', as: 'my_appointments'
  get 'appointment-search', to: 'appointments#search'
  get 'incomplete-appointments', to: 'appointments#incomplete'

  resources :volunteers
  resources :conversations

  scope module: 'static' do
    get :home
    get :team
    get :donate
    get :contact
  end

  post :contact, to: 'static#contact_submit'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :users do
    collection do
      get :new_volunteer
      post :create_volunteer
      get 'my-volunteers', action: :my_volunteers
      get 'pending-volunteers', action: :my_pending_volunteers
    end
  end

  resources :conversations do
    member do
      post :delete
    end
  end

  get 'dashboard', to: 'dashboard#show'
  get 'pending', to: 'dashboard#pending'
  get 'profile', to: 'dashboard#profile'
  get 'aggregate-report', to: 'dashboard#aggregate_report'
  patch 'change_password', to: 'dashboard#change_password', as: 'change_password'

  root 'static#home'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  # Default Scope
  # Constants
  STATUS = [["Must Contact Consumer for Follow Up", "followup_needed"],
            ["Referred Consumer to NJ Family Care", "referred_njfc"],
            ["Referred Consumer to SHIP Counselor", "referred_ship"],
            ["Referred Consumer to CAC Assister Organization", "referred_cac_org"],
            ["Referred Consumer to Navigator Organization", "referred_navigator_org"],
            ["Confirmed Consumer's Insurance Needs Are Met", "confirmed_needs_met"],
            ["Do Not Contact Consumer Again", "do_not_contact"]]

  COVERAGE = [["I do not currently have coverage", "none"],
              ["I need to renew coverage", "renew"],
              ["I am looking for better coverage", "better"],
              ["I know someone who needs coverage", "referral"]]

  # Attribute related macros
  # Associations
  belongs_to :user
  belongs_to :appointment

  # Validations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :state, presence: true


  # Callback
  # Other macros
  # Concerns
  include Deletable

  # Named scopes
  # Methods
  def name
    if self.first_name.present? and self.last_name.present?
      return "#{self.first_name} #{self.last_name}"
    else
      if self.first_name.present?
        return self.first_name
      elsif self.last_name.present?
        return self.last_name
      else
        return ''
      end
    end
  end

  def complete?
    return false
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user!
  before_action :set_conversation,    only: [:show, :edit, :update, :destroy]

  respond_to :html

  # GET /conversations
  # GET /conversations.json
  def index
    if current_user.admin?
      @conversations = Conversation.current
    else
      @conversations = current_user.conversations.current
    end
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = current_user.conversations.new(conversation_params)
    respond_to do |format|
      if @conversation.save
        format.html { redirect_to conversations_path, notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to conversations_path, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations
  # DELETE /conversations.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_conversation
      @conversation = Conversation.find_by_id(params[:id])
    end

    def conversation_params
        params.require(:conversation).permit(:first_name, :last_name, :email, :phone_number, :state, :address, :city, :zip_code, :notes, :current_coverage, :consented)
    end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.haml
= form_for @conversation, html: { class: 'form-horizontal' } do |f|
  - if @conversation.errors.any?
    #error_explanation
      %h2
        = pluralize(@conversation.errors.count, "error")
        prohibited this conversation from being saved:
      %ul
        - @conversation.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :appointment_id, nil, class: 'control-label col-md-2'
    .col-md-10
      = f.select :appointment_id, Appointment.where(date: Date.current).pluck(:location, :id), {}, class: 'form-control'
  .form-group
    = f.label :first_name, 'First name', class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :first_name, class: 'form-control'
  .form-group
    = f.label :last_name, 'Last name', class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :last_name, class: 'form-control'
  .form-group
    = f.label :email, 'Email address', class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :phone_number, 'Phone number', class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :phone_number, class: 'form-control'
  .form-group
    = f.label :address, 'Address', class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :address, class: 'form-control'
  .form-group
    = f.label :city, 'City', class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :city, class: 'form-control'
  .form-group
    = f.label :zip_code, 'Zip', class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :zip_code, class: 'form-control'
  .form-group
    = f.label :state, 'Status', class: 'control-label col-md-2'
    .col-md-10
      = f.select :state, [['---', nil]] + Conversation::STATUS, {}, class: 'form-control'
  .form-group
    = f.label :current_coverage, 'Which applies most?', class: 'control-label col-md-2'
    .col-md-10
      = f.select :current_coverage, [['---', nil]] + Conversation::COVERAGE, {}, class: 'form-control'
  .form-group
    = f.label :notes, 'Additional Notes', class: 'control-label col-md-2'
    .col-md-10
      = f.text_area :notes, class: 'form-control'
  .form-group
    .col-md-10.col-md-offset-2
      .checkbox
        %label
          = f.check_box :consented
          By completing this form, you agree that your information above may be shared with Be Jersey Strong and its partners to assist you.
  .form-group
    .col-md-10.col-md-offset-2
      = f.submit nil, class: 'btn btn-primary'

app/views/conversations/edit.html.haml
.content-header
  .container
    %h1 Editing Conversation
    %p
      = link_to 'Show', @conversation
      %span.white
        |
      = link_to 'Back', conversations_path

.container
  .content-container
    = render 'form'

app/views/conversations/index.html.haml
.content-header
  .container
    %h1 Connections
    %p= link_to 'Back to Dashboard', dashboard_path

.container
  .content-container
    %h2.primary-red Your Connections
    %br
    %table.table.table-striped
      %thead
        %tr
          %th First Name
          %th Last Name
          %th Email
          %th Phone Number
          %th Status
          %th{ colspan: 2 }
      %tbody
        - @conversations.each do |conversation|
          %tr
            %td= conversation.first_name if conversation.first_name.present?
            %td= conversation.last_name if conversation.last_name.present?
            %td= conversation.email if conversation.email.present?
            %td= conversation.phone_number if conversation.phone_number.present?
            %td= conversation.state if conversation.state.present?
            %td= link_to 'Edit', edit_conversation_path(conversation)
            %td= link_to 'Delete', conversation_path(conversation), method: :delete, data: { confirm: 'Are you sure?' }
    = link_to 'New Conversation', new_conversation_path, class: 'btn btn-primary'

- if current_user.campus_captain?
  .container
    .content-container
      %h2.primary-red Campus Connections
      %br
      %table.table.table-striped
        %thead
          %tr
            %th First Name
            %th Last Name
            %th Email
            %th Phone Number
            %th Status
            %th Volunteer
        %tbody
          - User.where(school: current_user.school).each do |volunteer|
            - volunteer.conversations.current.each do |conversation|
              %tr
                %td= conversation.first_name if conversation.first_name.present?
                %td= conversation.last_name if conversation.last_name.present?
                %td= conversation.email if conversation.email.present?
                %td= conversation.phone_number if conversation.phone_number.present?
                %td= conversation.state if conversation.state.present?
                %td= conversation.user.name
            %tr.info
              %td
              %td
              %td
              %td
              %td
              %td
      = link_to 'New Connection', new_conversation_path, class: 'btn btn-primary'

app/views/conversations/new.html.haml
.content-header
  .container
    %h1 New Connection
    %p= link_to 'Back to all connections', conversations_path

.container
  .content-container
    = render 'form'

app/views/conversations/show.html.haml
.content-header
  .container
    %h1
      Conversation with
      = @conversation.name
    %p
      = link_to 'Edit', edit_conversation_path(@conversation)
      %span.white
        |
      = link_to 'Back', conversations_path

.container
  .content-container
    %p.lead= "This conversation started on #{@conversation.created_at.strftime('%m/%d/%y')} at #{@conversation.created_at.strftime('%l:%M%P')}"

    %table.table.table-striped
      %thead
        %th First Name
        %th Last Name
        %th Email
        %th Phone Number
        %th Status
      %tbody
        %td= @conversation.first_name if @conversation.first_name.present?
        %td= @conversation.last_name if @conversation.last_name.present?
        %td= @conversation.email if @conversation.email.present?
        %td= @conversation.phone_number if @conversation.phone_number.present?
        %td= @conversation.state if @conversation.state.present?