config/routes.rb
Rails.application.routes.draw do

  resources :volunteer_resources do
    member do
      get :file
    end
  end

  get 'resources', to: 'dashboard#resources'
  resources :answers
  resources :questions

  resources :schools do
    collection do
      get 'my-school', action: :my_school
    end
  end

  resources :appointments
  get 'my-appointments', to: 'appointments#my_appointments', as: 'my_appointments'
  get 'appointment-search', to: 'appointments#search'
  get 'incomplete-appointments', to: 'appointments#incomplete'

  resources :volunteers
  resources :conversations

  scope module: 'static' do
    get :home
    get :team
    get :donate
    get :contact
  end

  post :contact, to: 'static#contact_submit'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :users do
    collection do
      get :new_volunteer
      post :create_volunteer
      get 'my-volunteers', action: :my_volunteers
      get 'pending-volunteers', action: :my_pending_volunteers
    end
  end

  resources :conversations do
    member do
      post :delete
    end
  end

  get 'dashboard', to: 'dashboard#show'
  get 'pending', to: 'dashboard#pending'
  get 'profile', to: 'dashboard#profile'
  get 'aggregate-report', to: 'dashboard#aggregate_report'
  patch 'change_password', to: 'dashboard#change_password', as: 'change_password'

  root 'static#home'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  # Default Scope
  # Constants
  # Attribute related macros
  # Associations
  belongs_to :user
  has_many :conversations

  # Validations
  validates :user_id, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :date, presence: true
  validates :address_line_one, presence: true
  validates :zipcode, presence: true
  validates :city, presence: true
  validates :location, presence: true

  # Callback
  # Other macros
  # Concerns
  include Deletable

  # Named scopes
  scope :incomplete, -> { current.where("conversation_count IS NULL or contact_card_count IS NULL or referral_count IS NULL or followup_call_count IS NULL") }

  # Methods
  def title
    location + ' with ' + user.first_name
  end

  def formatted_date
    date.strftime("%b %d, %Y")
  end

  def formatted_time
    start_time.strftime("%l:%M%P") + ' - ' + end_time.strftime("%l:%M%P")
  end

  def formatted_address
    street_address + '<br />' + city + ' NJ, ' + zipcode
  end

  def street_address
    address_line_two.present? ? address_line_one + '<br />' + address_line_two : address_line_one
  end

  def complete?
    conversation_count.present? && contact_card_count.present? && referral_count.present? && followup_call_count.present? && confirmed_enrollment_count.present?
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :search]
  before_action :check_user!, except: [:show, :search]
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    redirect_to my_appointments_path and return unless current_user.campus_captain?
    school_users = User.where(school: current_user.school).pluck(:id)
    @appointments = Appointment.where(user_id: school_users).order(:date)
  end

  def my_appointments
    @appointments = current_user.appointments.current.order(:date)
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  def search
    @appointments = Appointment.order(:zipcode).where(zipcode: params[:zipcode])
  end

  def incomplete
    @appointments = current_user.appointments.incomplete
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.where(created_by_id: current_user.id).new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.where(created_by_id: current_user.id).new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date, :start_time, :end_time, :completed, :deleted, :user_id, :location, :address_line_one, :address_line_two, :zipcode, :city, :results, :conversation_count, :contact_card_count, :referral_count, :followup_call_count, :confirmed_enrollment_count)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.haml
.appointment-container
  %h3= appointment.title
  %h4.primary-red= appointment.formatted_date
  %h5.primary-red= appointment.formatted_time
  = simple_format appointment.formatted_address, class: 'small'

app/views/appointments/_form.html.haml
= form_for @appointment, html: { class: 'form-horizontal' } do |f|
  - if @appointment.errors.any?
    #error_explanation.bs-callout.bs-callout-danger
      %h2
        = pluralize(@appointment.errors.count, "error")
        prohibited this shift from being saved:
      %ul
        - @appointment.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :date, nil, class: 'control-label col-md-2'
    .col-md-10
      = f.date_field :date, placeholder: 'yyyy-mm-dd', class: 'form-control'
      Please enter as
      %strong yyyy-mm-dd
  .form-group
    = f.label :start_time, nil, class: 'control-label col-md-2'
    .col-md-10
      = f.time_field :start_time, placeholder: 'hh:mm am/pm', class: 'form-control'
      Please enter as
      %strong hh:mm am/pm
  .form-group
    = f.label :end_time, nil, class: 'control-label col-md-2'
    .col-md-10
      = f.time_field :end_time, placeholder: 'hh:mm am/pm', class: 'form-control'
      Please enter as
      %strong hh:mm am/pm
  - if current_user.campus_captain?
    .form-group
      = f.label :user_id, 'Volunteer', class: 'control-label col-md-2'
      .col-md-10
        = f.select :user_id, User.where(school: current_user.school).collect{ |u| ["#{u.first_name} #{u.last_name} #{'(' + u.languages + ')' if u.languages.present?}", u.id]}, {}, class: 'form-control'
  - else
    = f.hidden_field :user_id, value: current_user.id
  .form-group
    = f.label :location, nil, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :location, class: 'form-control'
  .form-group
    = f.label :address_line_one, nil, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :address_line_one, class: 'form-control'
  .form-group
    = f.label :address_line_two, nil, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :address_line_two, class: 'form-control'
  .form-group
    = f.label :zipcode, nil, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :zipcode, class: 'form-control'
  .form-group
    = f.label :city, nil, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :city, class: 'form-control'
  - if @appointment.new_record?
    .form-group
      .col-md-10.col-md-offset-2
        = f.submit 'Create Shift', class: 'btn btn-primary'
  - else
    %hr
    .form-group
      = f.label :conversation_count, 'How many conversations did you have?', class: 'control-label col-md-4'
      .col-md-8
        = f.number_field :conversation_count, class: 'form-control'
    .form-group
      = f.label :contact_card_count, 'How many contact cards did you collect?', class: 'control-label col-md-4'
      .col-md-8
        = f.number_field :contact_card_count, class: 'form-control'
    .form-group
      = f.label :referral_count, 'How many referrals did you give?', class: 'control-label col-md-4'
      .col-md-8
        = f.number_field :referral_count, class: 'form-control'
    .form-group
      = f.label :followup_call_count, 'How many follow-up calls have you made/will you make?', class: 'control-label col-md-4'
      .col-md-8
        = f.number_field :followup_call_count, class: 'form-control'
    .form-group
      = f.label :confirmed_enrollment_count, 'How many enrollments did you confirm?', class: 'control-label col-md-4'
      .col-md-8
        = f.number_field :confirmed_enrollment_count, class: 'form-control'
    .form-group
      = f.label :results, 'Please add any other notes about this shift', class: 'control-label col-md-4'
      .col-md-8
        = f.text_area :results, class: 'form-control'
    .form-group
      .col-md-8.col-md-offset-4
        = f.submit 'Save Shift', class: 'btn btn-primary'

app/views/appointments/edit.html.haml
.content-header
  .container
    %h1 Editing Shift
    %p
      = link_to 'Show', @appointment
      %span.white
        |
      = link_to 'Back', appointments_path
.container
  .content-container
    = render 'form'

app/views/appointments/incomplete.html.haml
.content-header
  .container
    %h1 Incomplete Shifts
    %p= link_to 'Back to all shifts', appointments_path

.container
  - @appointments.each do |appointment|
    .row
      .col-sm-8
        = render appointment
      .col-sm-4
        = link_to 'Add missing information', edit_appointment_path(appointment), class: 'btn btn-primary'

app/views/appointments/index.html.haml
.content-header
  .container
    %h1 Shifts near your Campus
    %p= link_to 'Back to Dashboard', dashboard_path

.container
  .content-container
    - @appointments.each do |appointment|
      = render appointment
      = link_to 'Edit', edit_appointment_path(appointment)
      |
      = link_to 'Delete', appointment, method: :delete, data: { confirm: 'Are you sure?' }
      %br
      %br
    = link_to 'New Shift', new_appointment_path, class: 'btn btn-primary'

app/views/appointments/my_appointments.html.haml
.content-header
  .container
    %h1 My Shifts

.container
  - @appointments.each do |appointment|
    = render appointment

app/views/appointments/new.html.haml
.content-header
  .container
    %h1 New Shift
    = link_to 'Back to all shifts', appointments_path

.container
  .content-container
    = render 'form'

app/views/appointments/search.html.haml
.content-header
  .container
    %h1 Shifts

.container
  .content-container
    = form_tag appointment_search_path, method: :get, class: 'form-inline' do
      = label_tag 'Enter your zipcode: ', nil, class: 'control-label'
      &nbsp;
      = text_field_tag 'zipcode', params[:zipcode], class: 'form-control'
      = submit_tag 'Search', class: 'btn btn-primary', name: nil
    %br
    %br
    = render @appointments if @appointments.present?

app/views/appointments/show.html.haml
.content-header
  .container
    %h1 Shift
    %p.white
      = link_to 'Edit', edit_appointment_path(@appointment)
      |
      = link_to 'Back', appointments_path
.container
  .col-md-8
    = render @appointment
  .col-md-4
    - if @appointment.complete?
      %h4 Complete
      %ul
        %li= pluralize(@appointment.conversation_count, 'conversation')
        %li= pluralize(@appointment.contact_card_count, 'contact card')
        %li= pluralize(@appointment.referral_count, 'referral')
        %li= pluralize(@appointment.followup_call_count, 'follow-up call')
      %p= @appointment.results
    - else
      %h4 Incomplete