config/routes.rb
Rails.application.routes.draw do

  resources :volunteer_resources do
    member do
      get :file
    end
  end

  get 'resources', to: 'dashboard#resources'
  resources :answers
  resources :questions

  resources :schools do
    collection do
      get 'my-school', action: :my_school
    end
  end

  resources :appointments
  get 'my-appointments', to: 'appointments#my_appointments', as: 'my_appointments'
  get 'appointment-search', to: 'appointments#search'
  get 'incomplete-appointments', to: 'appointments#incomplete'

  resources :volunteers
  resources :conversations

  scope module: 'static' do
    get :home
    get :team
    get :donate
    get :contact
  end

  post :contact, to: 'static#contact_submit'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :users do
    collection do
      get :new_volunteer
      post :create_volunteer
      get 'my-volunteers', action: :my_volunteers
      get 'pending-volunteers', action: :my_pending_volunteers
    end
  end

  resources :conversations do
    member do
      post :delete
    end
  end

  get 'dashboard', to: 'dashboard#show'
  get 'pending', to: 'dashboard#pending'
  get 'profile', to: 'dashboard#profile'
  get 'aggregate-report', to: 'dashboard#aggregate_report'
  patch 'change_password', to: 'dashboard#change_password', as: 'change_password'

  root 'static#home'

end

app/views/layouts/_flash_messages.html.haml
- if flash[:notice]
  .flash-notice
    .lead.centered
      = flash[:notice].html_safe
- if flash[:alert]
  .flash-alert
    .lead.centered
      = flash[:alert].html_safe
- if flash[:warning]
  .flash-warning
    .lead.centered
      = flash[:warning].html_safe

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    .col-sm-3.hidden-xs
      %ul
        %p &copy; 2015 Be Jersey Strong
        %p.address Some Building
        %p.address Some Street
        %p.address Trenton, NJ 08601
    .col-sm-2.col-xs-3
      %ul
        %p BJS
        %li Who We Are
        %li What We Do
        %li Why We Do It
    .col-sm-2.col-xs-3
      %ul
        %p.small About
        %li Health Care
        %li New Jersey
        %li Grassroots
    .col-sm-2.col-xs-6
      %ul
        %p.f300.small{style: 'margin-left:5px;'} Contact Us
    .col-md-2.col-md-offset-1.col-sm-3.col-sm-offset-0.hidden-xs

app/views/layouts/_navigation_left.html.haml
%ul
	%li
		= link_to 'Our Team', team_path
	%li
		= link_to 'Donate', donate_path
	%li
		= link_to 'Contact', contact_path

app/views/layouts/_navigation_top.html.haml
%nav.navbar.navbar-default
	%button.navbar-toggle.visible-xs{"data-object" => 'navbar-collapse', style: 'display: inline-block'}
		%span.sr-only Toggle navigation
		%span.icon-bar
		%span.icon-bar
		%span.icon-bar
	.container
		.brand
			= link_to root_path do
				= image_tag 'img/Be-Jersey-Strong-05.png', class: 'img-responsive', width: '200px', style: 'float:left;'
		%ul.nav.navbar-nav.hidden-xs
			%li
				= link_to 'Home', root_path
			%li
				= link_to 'Our Team', team_path
			%li
				= link_to 'Donate', donate_path
			%li
				= link_to 'Contact', contact_path
			%li
				= link_to 'Find Local Help', 'http://www.covernj.org/aca-calendar-of-events.html', target: '_blank'
		%ul.nav.navbar-nav.pull-right
			- if current_user
				%li
					= link_to dashboard_path do
						%span.glyphicon.glyphicon-home{ style: 'font-size: 18px'}
				%li
					= link_to destroy_user_session_path, method: :delete do
						Logout
			- else
				%li
					= link_to 'Volunteer Login', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Be Jersey Strong
		%meta{ charset: 'utf-8'}
		%meta{ content: 'IE=Edge,chrome=1', http: {equiv: 'X-UA-Compatible'}}
		%meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
		= favicon_link_tag 'favicon.ico'
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
		%link{:href => "http://fonts.googleapis.com/css?family=Averia+Serif+Libre:300,400,700", :rel => "stylesheet", :type => "text/css"}
		%link{:href => "//cdn-images.mailchimp.com/embedcode/classic-081711.css", :rel => "stylesheet", :type => "text/css"}
%body
	= render partial: 'layouts/navigation_top'
	#container-main.container-fluid{ style: 'margin: 0; padding: 0;' }
		#container-left
			= render partial: 'layouts/navigation_left'
		#container-right
			= render 'layouts/flash_messages'
			= yield
			%br
			%br
	-#= render partial: 'layouts/footer'

app/views/layouts/application_fullscreen.html.haml
!!!
%html
  %head
    %title Be Jersey Strong
    %meta{ charset: 'utf-8'}
    %meta{ content: 'IE=Edge,chrome=1', http: {equiv: 'X-UA-Compatible'}}
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "http://fonts.googleapis.com/css?family=Averia+Serif+Libre:300,400,700", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "//cdn-images.mailchimp.com/embedcode/classic-081711.css", :rel => "stylesheet", :type => "text/css"}
%body
  = render partial: 'layouts/navigation_top'
  #container-main.container-fluid{ style: 'margin: 0; padding: 0;' }
    #container-left
      = render partial: 'layouts/navigation_left'
    #container-right
      = render 'layouts/flash_messages'
      = yield
  -#= render partial: 'layouts/footer'